In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
b = np.array(range(10))
print(b)
print(type(b))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [5]:
c = np.arange(10)
print(c)
print(type(c))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [6]:
d = np.array(range(1,4), dtype=float)
print(d)
print(d.dtype)

[1. 2. 3.]
float64


In [8]:
import random

a1 = np.array([random.random() for i in range(10)])
print(a1)
print(a1.dtype)

[0.1065833  0.51486465 0.83804141 0.22053916 0.15008954 0.10771048
 0.45054076 0.9560436  0.70307975 0.02690863]
float64


In [10]:
#保留两位小数
a2 = np.round(a1, 2)
print(a2)

[0.11 0.51 0.84 0.22 0.15 0.11 0.45 0.96 0.7  0.03]


In [11]:
import numpy as np

a1 = np.arange(12)
print(a1)
print(a1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [13]:
a2 = a1.reshape(3,4)
print(a2)
print(a2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [15]:
a3 = a1.reshape(2,2,3)
print(a3)
print(a3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [16]:
#展平
a3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
#转置
a2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [20]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a4 = np.arange(72).reshape(8,9)
a4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71]])

In [29]:
#取某一行
print(a4[2])

[18 19 20 21 22 23 24 25 26]


In [30]:
#取连续几行
print(a4[2:5])

[[18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]


In [31]:
#取任意某几行
print(a4[[2,3,5]])

[[18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [45 46 47 48 49 50 51 52 53]]


In [33]:
#取某一列
print(a4[:,2])

[ 2 11 20 29 38 47 56 65]


In [34]:
#取连续几列
print(a4[:,2:5])

[[ 2  3  4]
 [11 12 13]
 [20 21 22]
 [29 30 31]
 [38 39 40]
 [47 48 49]
 [56 57 58]
 [65 66 67]]


In [35]:
#取任意某几列
print(a4[:,[2,3,5]])

[[ 2  3  5]
 [11 12 14]
 [20 21 23]
 [29 30 32]
 [38 39 41]
 [47 48 50]
 [56 57 59]
 [65 66 68]]


In [36]:
#取某行某列
print(a4[1,1])

10


In [39]:
#取某几行某几列
print(a4[2:5,1:4])

[[19 20 21]
 [28 29 30]
 [37 38 39]]


In [41]:
#取多个不相邻的点[0,0],[2,1]
print(a4[[0,2,7],[0,1,8]])

[ 0 19 71]


In [42]:
a4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71]])

In [44]:
#如果a4的元素值小于36，赋0，否则赋1
a5 = np.where(a4<36,0,1)
a5

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
#小于17的替换为17，大于54的替换成54
a6 = a4.clip(17,54)
a6

array([[17, 17, 17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17, 17, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 54, 54, 54, 54, 54, 54, 54, 54],
       [54, 54, 54, 54, 54, 54, 54, 54, 54]])

In [50]:
t1 = np.arange(12).reshape(2,6)
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [51]:
t2 = np.arange(12,24).reshape(2,6)
t2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
#竖直拼接
t3 = np.vstack((t1, t2))
t3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [54]:
#水平拼接
t4 = np.hstack((t1, t2))
t4

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

In [55]:
#数组的行列交换
#行交换
t3[[1,2],:] = t3[[2,1],:]
t3

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [56]:
#列交换
t3[:,[1,2]] = t3[:,[2,1]]
t3

array([[ 0,  2,  1,  3,  4,  5],
       [12, 14, 13, 15, 16, 17],
       [ 6,  8,  7,  9, 10, 11],
       [18, 20, 19, 21, 22, 23]])

In [57]:
#创建一个全为0的数组
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
#创建一个全为1的数组
one = np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
#创建一个对角矩阵
diag = np.diag([1,2,3])
diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [64]:
#创建一个对角线为1的方针
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
#获取最大值最小值位置
print(np.argmax(t3, axis=1))

[5 5 5 5]


In [68]:
t3

array([[ 0,  2,  1,  3,  4,  5],
       [12, 14, 13, 15, 16, 17],
       [ 6,  8,  7,  9, 10, 11],
       [18, 20, 19, 21, 22, 23]])

In [70]:
print(np.argmin(t3,axis=1))

[0 0 0 0]


In [72]:
#numpy内置random，直接生成随机数组
r = np.random.randint(1,20,(2,10))
r

array([[17, 15, 14, 16, 19,  1,  1, 11, 10, 12],
       [ 2,  8, 15,  3, 16, 12,  4, 11,  2,  4]])