In [1]:
import numpy as np
list1 = [3.14, 2.17, 0, 1, 2]
nd1 = np.array(list1)
print(nd1)
print(type(nd1))

[3.14 2.17 0.   1.   2.  ]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
list2 = [[3.14, 2.17, 0, 1, 2], [1, 2, 3, 4, 5]]
nd2 = np.array(list2)
print(nd2)
print(type(nd2))

[[3.14 2.17 0.   1.   2.  ]
 [1.   2.   3.   4.   5.  ]]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

nd5 = np.random.random([3, 3])
print(nd5)
print(type(nd5))

[[0.77284096 0.58126235 0.89996499]
 [0.37052975 0.20651262 0.31865204]
 [0.36542842 0.70181133 0.18882855]]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

np.random.seed(123)
nd5_1 = np.random.randn(2, 3)
print(nd5_1)
np.random.shuffle(nd5_1)
print("随机打乱后数据")
print(nd5_1)
print(type(nd5_1))

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
随机打乱后数据
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

#生成全是0的3*3矩阵
nd6 = np.zeros([3, 3])
print(nd6)
#生成全是1的3*3矩阵
nd7 = np.ones([3, 3])
print(nd7)
#生成3阶的单位矩阵
nd8 = np.eye(3)
print(nd8)
#生成3阶对角矩阵
print(np.diag([1, 2, 3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
import numpy as np
nd9 = np.random.random([5, 5])
np.savetxt(X = nd9, fname = './test2.txt')
nd10 = np.loadtxt('./test2.txt')
print(nd10)

[[0.02798196 0.17390652 0.15408224 0.07708648 0.8898657 ]
 [0.7503787  0.69340324 0.51176338 0.46426806 0.56843069]
 [0.30254945 0.49730879 0.68326291 0.91669867 0.10892895]
 [0.49549179 0.23283593 0.43686066 0.75154299 0.48089213]
 [0.79772841 0.28270293 0.43341824 0.00975735 0.34079598]]


In [12]:
import numpy as np

print(np.arange(10))
print(np.arange(0, 10))
print(np.arange(1, 4, 0.5))
print(np.arange(9, -1, -1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]


In [16]:
import numpy as np

np.random.seed(2018)
nd11 = np.random.random([10])
print(nd11)
#获取指定位置的数据，获取第4个元素
print(nd11[3])
#截取一段数据
print(nd11[3:6])
#截取固定间隔数据
print(nd11[1:6:2])
#倒序取数
print(nd11[::-2])
#截取一个多维数组的一个区域内数据
nd12 = np.arange(25).reshape([5, 5])
print(nd12)
print(nd12[1:3, 1:3])
#截取一个多维数组中，数值在一个值域之内的数据
print(nd12[(nd12>3)&(nd12<10)])
#截取多维数组中，指定的行，如读取第2,3行
print(nd12[[1,2]])
#截取多维数组中，指定的列，如读取第2,3列
print(nd12[:, 1:3])

[0.88234931 0.10432774 0.90700933 0.3063989  0.44640887 0.58998539
 0.8371111  0.69780061 0.80280284 0.10721508]
0.3063988986063515
[0.3063989  0.44640887 0.58998539]
[0.10432774 0.3063989  0.58998539]
[0.10721508 0.69780061 0.58998539 0.3063989  0.10432774]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 6  7]
 [11 12]]
[4 5 6 7 8 9]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [17]:
import numpy as np
from numpy import random as nr

a = np.arange(1, 25, dtype = float)
c1 = nr.choice(a, size = (3, 4))
c2 = nr.choice(a, size = (3, 4), replace=False)
#下式中参数p指定每个元素对应的抽取概率，默认为每个元素被抽取的概率相同
c3 = nr.choice(a, size = (3, 4), p = a / np.sum(a))
print("随机可重复抽取")
print(c1)
print("随机但不重复抽取")
print(c2)
print("随机但按指定概率抽取")
print(c3)

随机可重复抽取
[[18.  1.  7. 14.]
 [22. 23. 24.  1.]
 [24.  9.  8. 10.]]
随机但不重复抽取
[[ 3. 20.  4. 10.]
 [13. 22.  5. 17.]
 [ 8. 15. 24.  2.]]
随机但按指定概率抽取
[[20.  5. 12. 18.]
 [18. 15.  7. 14.]
 [23. 21. 24. 18.]]


In [21]:
import numpy as np

nd14 = np.arange(9).reshape([3,3])
print(nd14)

#矩阵转置
print(np.transpose(nd14))

#矩阵乘法
a = np.arange(12).reshape([3, 4])
print(a)
b = np.arange(8).reshape([4, 2])
print(b)
print(a.dot(b))

#求矩阵的迹
print(nd14.trace())
#计算矩阵行列式
print(np.linalg.det(nd14))

#计算逆矩阵
c = np.random.random([3, 3])
print(c)
print(np.linalg.solve(c, np.eye(3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 28  34]
 [ 76  98]
 [124 162]]
12
0.0
[[0.49004436 0.00303589 0.84366215]
 [0.54368872 0.13869147 0.08572875]
 [0.40161209 0.82697863 0.80616256]]
[[ 0.11650638  1.97986434 -0.33246808]
 [-1.15011756  0.16012924  1.18658819]
 [ 1.12177409 -1.15058794  0.18884545]]


In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a, b)
print(c)
d = np.concatenate([a, b])
print(d)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [23]:
import numpy as np

a = np.arange(4).reshape([2, 2])
b = np.arange(4).reshape([2, 2])

#按行合并
c = np.append(a, b, axis=0)
print(c)
print("合并后数据维度", c.shape)

#按列合并
d = np.append(a, b, axis=1)
print(d)
print("合并后数据维度", d.shape)

[[0 1]
 [2 3]
 [0 1]
 [2 3]]
合并后数据维度 (4, 2)
[[0 1 0 1]
 [2 3 2 3]]
合并后数据维度 (2, 4)


In [24]:
import numpy as np

nd15 = np.arange(6).reshape(2, -1)
print(nd15)
#按照列优先，展平
print("按列优先,展平")
print(nd15.ravel('F'))
#按照行优先，展平
print("按行优先,展平")
print(nd15.ravel())


[[0 1 2]
 [3 4 5]]
按列优先,展平
[0 3 1 4 2 5]
按行优先,展平
[0 1 2 3 4 5]


In [27]:
import time
import math
import numpy as np

x = [i * 0.001 for i in np.arange(1000000)]
start = time.clock()
for i, t in enumerate(x):
    x[i] = math.sin(t)
print("math.sin:", time.clock() - start)

x = [i * 0.001 for i in np.arange(1000000)]
x = np.array(x)
start = time.clock()
np.sin(x)
print("numpy.sin:", time.clock() - start)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  if __name__ == '__main__':


math.sin: 0.4730549999985669
numpy.sin: 0.018625799999426818


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  from ipykernel import kernelapp as app


In [28]:
import time
import numpy as np

x1 = np.random.rand(1000000)
x2 = np.random.rand(1000000)

##使用循环计算向量点积
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()    
print("dot = " + str(dot) + "\n for loop----- Computation time = " + str(1000*(toc - tic)) + "ms")

##使用numpy函数求点积
tic = time.process_time()
dot = 0
dot = np.dot(x1, x2)
toc = time.process_time()    
print("dot = " + str(dot) + "\n verctor version----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 249695.95496750838
 for loop----- Computation time = 812.5ms
dot = 249695.95496750379
 verctor version----- Computation time = 0.0ms


In [29]:
import numpy as np

a = np.arange(10)
b = np.arange(10)
#两个shape相同的数组相加
print(a + b)
#一个数组与标量叠加
print(a + 3)
#两个向量相乘
print(a * b)

#多维数组之间的运算
c = np.arange(10).reshape(5, 2)
d = np.arange(2).reshape(1, 2)
#将d数组进行复制扩充为【5,2】
print(c + d)

[ 0  2  4  6  8 10 12 14 16 18]
[ 3  4  5  6  7  8  9 10 11 12]
[ 0  1  4  9 16 25 36 49 64 81]
[[ 0  2]
 [ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]]
